baseURL = 'https://amanreasoned.com/'
languageCode = 'en-us'
title = 'amanreasoned'
theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]
enableRobotsTXT = true
cleanDestinationDir=true
pluralizelisttitles=false
[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5
[menu]
[[menu.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10
[[menu.main]]
    name = 'Tech'
    pageRef = '/tech'
    weight = 20
[taxonomies]
  category = 'categories'
  series = 'series'
  tag = 'tags'