baseURL = 'https://amanreasoned.com/'
languageCode = 'en-us'
title = 'amanreasoned'
theme = 'ananke'
enableRobotsTXT = true
cleanDestinationDir=true
pluralizelisttitles=false
[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5
[menu]
[[menu.main]]
    name = 'Home'
    pageRef = '/'
    weight = 1
[[menu.main]]
    name = 'Tech'
    pageRef = '/tech'
    weight = 2
[[menu.main]]
    name = 'Series'
    pageRef = '/series'
    weight = 3
[[menu.main]]
    name = 'About'
    pageRef = '/about'
    weight = 4
[taxonomies]
  category = 'categories'
  series = 'series'
  tag = 'tags'
[params]
  favicon = "favicon.jpeg"