baseURL = 'https://amanreasoned.com/'
languageCode = 'en-us'
title = 'amanreasoned'
theme = 'ananke'
enableRobotsTXT = true
[menu]
[[menu.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10
[[menu.main]]
    name = 'Tech'
    pageRef = '/tech'
    weight = 20
[taxonomies]
  category = 'categories'
  series = 'series'
  tag = 'tags'